# Generated by Django 4.1.4 on 2022-12-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incommonpanel', '0002_alter_document_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='catalog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='incommonpanel.catalog'),
        ),
    ]
