# Generated by Django 4.1.4 on 2022-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthsday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
